# Generated by Django 4.1.2 on 2023-02-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_iteminorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemInOrder',
        ),
    ]
